# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bjorn's Blog
tagline:             'random stuff'
description:         'A blog about mostly technology things.'
url:                 http://bjornl.im
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bjorn Lim
  url:               http://bjornl.im
  email:             mail@bjornl.im

# Custom vars
version:             1.0.0
